name: ui_tutorial

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # SVG
  flutter_svg: ^2.2.3

  # slide to act
  slide_to_act: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/fonts/




  fonts:
    - family: "Lato"
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-Light.ttf


